# Generated by Django 4.2.3 on 2023-07-22 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_rename_vitnumber_companyprofile_vatnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('carbonEmission', models.FloatField(default=0.0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(default='未知', max_length=50)),
                ('EName', models.CharField(default='Unknown', max_length=50)),
                ('carbonEmission', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('CName', 'EName')},
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('carbonEmission', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('carbonEmission', models.FloatField(default=0.0, editable=False)),
                ('company', models.ForeignKey(default='11111111', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='general.company')),
                ('materials', models.ManyToManyField(related_name='products', through='product.Component', to='product.material')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.material'),
        ),
        migrations.AddField(
            model_name='component',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.CreateModel(
            name='AbstractLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logType', models.CharField(choices=[('TRANSPORTATION', 'transportation'), ('ITEM', 'item')], default='TRANSPORTATION', max_length=50)),
                ('carbonEmission', models.FloatField(default=0.0, editable=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.abstractlog',),
        ),
        migrations.CreateModel(
            name='LogT',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.abstractlog',),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('product', 'material')},
        ),
        migrations.CreateModel(
            name='LogTProfile',
            fields=[
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.logt')),
                ('distance', models.FloatField(blank=True, default=0.0)),
                ('transportation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='product.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='LogIProfile',
            fields=[
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.logi')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
