# Generated by Django 4.2.3 on 2023-07-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_transportation'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtprofile',
            name='transportation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='general.transportation'),
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
    ]
