# Generated by Django 4.2.3 on 2023-07-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('categoryType', models.CharField(choices=[('MATERIAL', 'material'), ('PRODUCT', 'product')], default='MATERIAL', editable=False, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='product.category')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoryType': 'MATERIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoryType': 'PRODUCT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category'),
        ),
        migrations.DeleteModel(
            name='MaterialCategory',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.category',),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.category',),
        ),
    ]
