# Generated by Django 4.2.3 on 2023-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productcategory_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractlog',
            name='logType',
            field=models.CharField(choices=[('TRANSPORTATION', 'transportation'), ('ITEM', 'item')], default='TRANSPORTATION', max_length=50),
        ),
    ]
