# Generated by Django 4.2.3 on 2023-07-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='description',
        ),
    ]
