# Generated by Django 4.2.3 on 2023-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_cname_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('nameField', models.CharField(default='name', max_length=50)),
                ('coeField', models.CharField(default='coe', max_length=50)),
                ('dateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
