# Generated by Django 4.2.3 on 2023-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_uploadmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='weight',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadmaterial',
            name='unitField',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
