# Generated by Django 4.2.3 on 2023-09-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_image_product_isterminated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isTerminated',
            new_name='isActivated',
        ),
    ]
