# Generated by Django 4.2.3 on 2023-09-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_isterminated_product_isactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isActivated',
            field=models.BooleanField(default=1),
        ),
    ]
