# Generated by Django 4.2.3 on 2023-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='vatNumber',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vitNumber',
            field=models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
