# Generated by Django 4.2.3 on 2023-07-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='vitNumber',
            new_name='vatNumber',
        ),
    ]
