# Generated by Django 4.2.3 on 2023-07-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_companyprofile_vatnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='vitNumber',
            new_name='vatNumber',
        ),
    ]
