# Generated by Django 4.2.3 on 2023-07-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_transportation_remove_logiprofile_log_and_more'),
        ('general', '0003_transportation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transportation',
        ),
    ]
