# Generated by Django 4.2.3 on 2023-07-26 03:02

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_profile_remove_normalprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Normal',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('company', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
