# Generated by Django 4.2.3 on 2023-07-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
