# Generated by Django 4.2.3 on 2023-08-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_remove_user_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'meta_key')},
        ),
    ]
